src/astroid.cc, src/config.cc, src/main_window.cc, src/main_window.hh, src/modes/edit_message.cc, src/modes/edit_message.hh, src/modes/forward_message.cc, src/modes/help_mode.cc, src/modes/help_mode.hh, src/modes/keybindings.cc, src/modes/keybindings.hh, src/modes/log_view.cc, src/modes/log_view.hh, src/modes/mode.cc, src/modes/mode.hh, src/modes/paned_mode.cc, src/modes/raw_message.cc, src/modes/raw_message.hh, src/modes/reply_message.cc, src/modes/reply_message.hh, src/modes/thread_index/thread_index.cc, src/modes/thread_index/thread_index.hh, src/modes/thread_index/thread_index_list_view.cc, src/modes/thread_index/thread_index_list_view.hh, src/modes/thread_view/thread_view.cc, src/modes/thread_view/thread_view.hh, src/proto.hh, src/utils/vector_utils.hh
set up configurable and customizable keybindings.
also, ref: #25.
=> fix #21: keybindings

History.txt, src/config.cc, src/modes/thread_index/thread_index.cc, src/modes/thread_index/thread_index.hh, src/modes/thread_index/thread_index_list_view.cc
=> ti: C-s cycle through sort order for thread_index, default is configurable

src/compose_message.cc, src/compose_message.hh
attempt to fix the occasional crashes in #58.
=> #58: emit thread_updated on main gui thread

src/config.cc, src/modes/thread_index/thread_index_list_cell_renderer.cc, src/modes/thread_index/thread_index_list_cell_renderer.hh
the main code was already there, i just added a config option to aktivate it
=> make background of selected item configurable

SConstruct, src/modes/thread_view/theme.cc, src/modes/thread_view/theme.hh
=> scons: optionally generate scss at build time and drop libsass dependency

src/modes/thread_view/thread_view.cc, ui/thread-view.scss
=> tv: show reply-to

src/utils/date_utils.cc, test/SConscript, test/mail/test_mail/date1.eml, test/mail/test_mail/date2.eml, test/test_dates.cc
=> test: add dates testing

src/modes/edit_message.cc
add error return check and react on it. seen due to the warning from the compiler that the error wasn't checked.
=> check error

src/modes/log_view.cc, src/utils/date_utils.cc
=> ulong -> unsigned long

src/main_window.cc, src/main_window.hh, src/modes/saved_searches.cc, src/modes/saved_searches.hh, src/modes/thread_index/query_loader.cc, src/modes/thread_index/query_loader.hh
=> Less db action

site_scons/site_tools/unittest.py, src/chunk.cc, src/chunk.hh, src/crypto.cc, src/crypto.hh, src/message_thread.cc, src/message_thread.hh, src/modes/edit_message.cc, src/modes/thread_view/thread_view.cc, test/foo1.key, test/foo2.key, test/test_crypto.cc
=> Crypto too many files

ui/icons/LICENSE
Added credits for the logo. Attribution to Ura Design
=> License for the logo

src/modes/thread_index/thread_index_list_view.cc
=> ti: use mail-reply-sender and mail-forward icons

History.txt, src/account_manager.cc, src/account_manager.hh, src/config.cc, src/config.hh, src/db.cc, src/db.hh, src/modes/forward_message.cc, src/modes/reply_message.cc
=> Query select from

History.txt, SConstruct, src/astroid.cc, src/astroid.hh, src/chunk.cc, src/compose_message.cc, src/crypto.cc, src/message_thread.cc, src/message_thread.hh, src/modes/edit_message.cc, src/modes/thread_view/thread_view.cc, src/utils/address.cc, src/utils/address.hh, src/utils/gmime/gmime-compat.cc, src/utils/gmime/gmime-compat.h, test/test_crypto.cc, test/test_dates.cc
=> Gmime 3 support

src/compose_message.cc, src/utils/gmime/gmime-compat.cc, src/utils/gmime/gmime-compat.h, tests/test_dates.cc
=> gmime2: set timezone in hours (not seconds)

History.txt, src/modes/thread_index/thread_index_list_cell_renderer.cc, src/modes/thread_index/thread_index_list_cell_renderer.hh
Only the marked message stuff from #336
=> Drop mark icon: Indicate marked message with background color in thread-index

src/modes/thread_index/thread_index_list_cell_renderer.cc
=> ti: do not set background color unnecessarily

History.txt, src/config.cc, src/modes/edit_message.cc
Add configure option: `mail.close_on_success`
=> em: Close page automatically after successful send

src/compose_message.cc, src/message_thread.cc, src/message_thread.hh, src/modes/edit_message.cc
=> fix #587: only messages that are being read should be processed

examples/poll.sh
https://github.com/astroidmail/astroid/wiki/Processing-mail doesn't exist.
=> fix broken link in example script

src/astroid.cc, src/main.cc, tests/test_common.hh
I added a redundant `include` to the main for readability, I hope that's fine for you.
=> Fix segmentation fault when quitting (#636)

CMakeLists.txt
=> Don't forget the include dir for notmuch

shell.nix
=> shell.nix: add ninja as dependency

src/modes/thread_view/webextension/tvextension.cc
Fixes #762 
Signed-off-by: Christian Heusel <christian@heusel.eu>
=> tvextension: Fix protobuf 30.0 compatibility issue
