astroidmail/astroid

- src/modes/thread_view/theme.cc
sass_delete_file_context also frees output_string. So we
need to copy output before deleting the context.
> Fix #60: test_theme failure due to use after free.

- src/astroid.cc
- src/astroid.hh
- src/main_window.cc
- src/modes/edit_message.cc
- src/modes/help_mode.cc
- src/modes/thread_view/thread_view.cc
astroid.cc still needs several seconds to compile, so I was
tempted to create a simple build_info.cc - but that seems to
be a little bit of overkill.
I also thought of removing Astroid::user_agent as it is not
used anywhere, but I don't know your plans for it ;)
> Speed up hacking by minimizing includes of build_config.hh

- src/config.cc
- src/modes/keybindings.cc
- src/modes/keybindings.hh
- src/modes/thread_index/thread_index.cc
- src/modes/thread_index/thread_index_list_view.cc
- src/utils/cmd.cc
- src/utils/cmd.hh
- test/.gitignore
- test/SConscript
- test/test_home/keybindings
- test/test_keybindings.cc
This implements #29 and allows custom shell commands to be bound to keys in astroid. For now there is only `thread_index.run`. This allows you to have a shell command be run with the `thread` as an argument. 
The run-hooks are configured through the keybindings file, the most rudimentary example which allows you to safely get the hang of it is to add a line like:
~/.config/astroid/keybindings:
```
thread_index.run(echo %1)=w
```
if you press `w` in the Thread Index the command `echo %1` will be run with `%1` replaced with the `thread`-id from the currently selected thread. 
A more useful example is to set up keybindings to toggle custom tags, first create a script that can toggle its given tag. In this example the `queue` tag:
~/.config/astroid/hooks/toggle (you can place this anywhere): …
> Run: add run shell-command hooks, starting out with thread_index.run

- History.txt
- src/astroid.cc
- src/astroid.hh
- src/command_bar.cc
- src/command_bar.hh
- src/config.cc
- src/config.hh
- src/main_window.cc
- src/modes/saved_searches.cc
- src/modes/saved_searches.hh
- src/modes/thread_index/thread_index.cc
#42
Open with `C-f`.
currently only startup queries are shown
The plan is to include:
this is getting pretty close to: https://notmuchmail.org/screenshots/#index1h3
> saved searches: show startup queries

- History.txt
- src/command_bar.cc
- src/command_bar.hh
- src/modes/thread_index/query_loader.cc
- src/modes/thread_index/query_loader.hh
- src/modes/thread_index/thread_index.cc
- src/modes/thread_index/thread_index_list_view.cc
- src/modes/thread_view/thread_view.cc
- src/modes/thread_view/thread_view.hh
Search in thread view using `/`.
You can search for text-strings in thread-view using `/` (I opted to not shadow `F`, but you can re-configure this yourself). Then browse the search-results with `N` and `P` (currently shadowing manual poll from thread-view). Stop searching and drop highlighting using `Escape`.
Focusing is a bit of a problem as there does not seem to be a way to get the position of the currently selected text (or the actual text without going through the clipboard). But whenever webkit scrolls the view to a new result it centers it, so when there is a scroll event during searching I focus the centered message, otherwise focus might be a bit off.
When searching all messages are expanded, otherwise hidden matches may be found when iterating over the results.
#141.
> Thread view search

- History.txt
- src/astroid.cc
- src/config.cc
- src/crypto.cc
- src/crypto.hh
- src/modes/thread_index/thread_index_list_cell_renderer.cc
- src/modes/thread_index/thread_index_list_cell_renderer.hh
- src/modes/thread_view/thread_view.cc
- src/utils/utils.cc
- src/utils/utils.hh
- src/utils/vector_utils.cc
- src/utils/vector_utils.hh
each tag is assigned a color based on the last 6 digits in the md5 sum
of the tag. the color is blended with a base color weighting the base
color with a coefficient of 0.5 to have colors oscilliate around the
base.
each tag will therefore always have the same color, since the last
digits are used it is unlikely that similar tags (and adjacent in the
listing) will have the same color.
the base color is configurable, the same is the weight. by setting the weight to 0 only the base color is used.
#139
> ti: vary tag color based on md5 hashing

- src/main_window.cc
- src/modes/thread_index/thread_index.cc
- src/modes/thread_index/thread_index_list_view.cc
- src/modes/thread_view/thread_view.cc
thread_index.label is now moved to thread_index.tag, update your custom
keybindings.
Changes to default keybindings:
```
main_window.next_page = b
main_window.next_page = l
main_window.previous_page = B
main_window.previous_page = h
main_window.close_page = C-w
main_window.close_page_force = C-W
main_window.open_new_window = C-o
main_window.search = o
thread_index.refine_query = O
thread_index.tag = +
thread_index.multi = ;
thread_index.multi.tag = +
thread_view.multi = ;
thread_view.tag_message = +
thread_view.flat = C-F
thread_view.search.search = C-f
```
thread_view.open is removed (used to be 'o'), it can all be achieved by
using Enter.
> fix #151: revamp default keybindings

- src/modes/thread_view/thread_view.cc
i consider <> as a convention / pattern to display / denote email addresses so i changed it in astroid accordingly. what do you think?
> change from () to <> for email display

- src/modes/thread_view/theme.cc
recent libsass (3.4) resets the original context when setting an option
(https://github.com/sass/libsass/issues/2257) causing the input_path to
be lost (#244). here we set the options directly on file_ctx which is a
subclass of options - this might break in the future if file_ctx no
longer sub-classes options. oh well.
> sass: set options directly on file_ctx to avoid options reset

- SConstruct
- src/main_window.cc
- src/main_window.hh
Open a drop-down terminal with '|', useful in combination with 'Y' and patches.
> Open drop-down terminal with '|'

- src/modes/thread_view/thread_view.cc
Extending the escaping mechanism from https://github.com/astroidmail/astroid/commit/0ff5fe1a70558c9f61001e9734e42d9df608f3d6 for people using periods in their notmuch tags.
> Escaping . characters for CSS auto-tag-classes

- src/poll.cc
- src/poll.hh
> poll: keep sigc::connection in poll thread, don't connect unused stdin

- History.txt
- src/command_bar.cc
- src/modes/thread_index/thread_index_list_view.cc
- src/modes/thread_view/thread_view.cc
- src/utils/vector_utils.cc
Skip the ',' as delimiter for tags. This makes it quicker to navigate and edit tags. Tags with spaces in them are not supported, but I dont think they were in the first place either. Opinions?
> cb: do not use ',' to delimit tags, only space

- src/account_manager.cc
- src/account_manager.hh
- src/compose_message.cc
- src/modes/edit_message.cc
- save_sent_to : make bfs::path, adjust related and expand '~'
- save_drafts_to  : make bfs::path, adjust related and expand '~'
- signature_file : expand '~'
> Locations to bfs::path and expand '~' consistency

- src/modes/edit_message.cc
- src/modes/edit_message.hh
- src/modes/thread_view/thread_view.cc
Initial resolve for issue #381  but probably needs a bit more, please
review.
- clarify help text for command
- support cc and bcc in recipient when composing to self
(bcc is probably not that useful here)
- adjust variable naming to clarify code
Added `EditMessage` with additional signature, probably a bit
overkill and could use just the one.
> Improve 'c' (compose to sender) command

- History.txt
- meson.build
- src/compose_message.cc
- src/compose_message.hh
- src/config.cc
- src/modes/edit_message.cc
- src/modes/edit_message.hh
- tests/test_markdown.cc
- ui/edit-message.glade
html and text.
This requires a markdown to html converter like
[marked](https://github.com/chjj/marked). The markdown processor should
read from stdin and output html to stdout.
TODO:
* Persistent markdown state over drafts (similar to signatures being
added twic)
* Always show HTML part when composing (would be great with a better
UI for showing alternative parts #408)
> Remember that you can toggle the alternative part with Ctrl+Space when in EditMode (usually done with Enter).
__Requires [marked](https://github.com/chjj/marked) to be installed.__
Works as an alternative to: #362.
> markdown: compose messages as markdown and send as multipart/alternative

- src/modes/edit_message.cc
- src/modes/edit_message.hh
Don't save the signature with the draft. 
(Temporary) solution for issue #234
> Do not save signature with draft

- src/config.cc
- src/poll.cc
- src/poll.hh
#452 
Either set new configuration option: poll.always_full_refresh = true or do `astroid --refresh 0`. Not really tested.
> poll: optionally do full refresh; also triggerbale by --refresh 0

- src/compose_message.cc
This is a very simplistic approach to solve #446. It just does not add `format=flowed` in the Content-Type header.
format=flowed causes some sick issues in combination with quoted-printable and special characters because astroid (or gmime) does no proper space stuffing to mitigate the automatic line breaks caused by quoted-printable. This can not be resolved by changes in the editor AFAIU. More about the problem in the issue.
Some people have raised that they would like to keep format=flowed as an option which isn't covered in this PR because I lack the skills to realise it. Nevertheless this PR solves an existing bug and doesn't really make new mails extremely ugly or something, so we could still work on adding an improved implementation of format=flowed later IMHO (except someone comes …
> Disable format=flowed as Content-Type for new mails

- History.txt
- src/actions/cmdaction.cc
- src/modes/keybindings.cc
- src/modes/keybindings.hh
- src/modes/thread_index/thread_index_list_view.cc
- src/modes/thread_view/thread_view.cc
- src/utils/cmd.cc
- src/utils/cmd.hh
- tests/test_home/keybindings
- tests/test_keybindings.cc
Use thread_view.run(cmd, undo_cmd)=w to specify a undo command for
hooks. undo_cmd takes the same arguments as cmd. Specifying no undo_cmd
is allowed and is equivalent to having and empty field in undo_cmd.
Escape ',' in your cmds with '\,'.
Need to be updated: https://github.com/astroidmail/astroid/wiki/User-defined-keyboard-hooks
> hooks: undo hooks

- CMakeLists.txt
- History.txt
- examples/astroid
- src/astroid.cc
- src/astroid.hh
- src/config.cc
- src/modes/thread_view/page_client.cc
- src/modes/thread_view/webextension/messages.proto
- src/modes/thread_view/webextension/tvextension.cc
- src/modes/thread_view/webextension/tvextension.hh
remove file log and add syslog. the multi-process design we have now
would require careful handling when output to one file.
syslog and stdout config options for the log are created. as well as one
config option for setting the log-level (fixes #419). the corresponding
log-level option is removed as executable argument. a --log-stdout
argument is added. and --disable-log still overrides.
> LogView does not work with only syslog backend.
> add syslog backend and make logging sinks and level configurable

- tests/run_test.sh
This is because on some systems, bash is not in
/bin/bash
Solution: use /usr/bin/env bash in the shebang
> Problem: tests/run-test.sh might fail

- CMakeLists.txt
The correct path is apps, not app*.
> cmake: fix scalable icon install path

- src/main_window.cc
- src/main_window.hh
Signal documented here: https://developer.gnome.org/gtkmm/stable/classGtk_1_1Widget.html#a3986616c9bc5ed3bb3bcc450ec80d54c
> fix #501: Add hook to signal_delete_event, ensure proper destruction of window

- src/message_thread.cc
- src/plugin/astroid_activatable.c
- src/plugin/astroid_activatable.h
- src/plugin/manager.cc
- src/plugin/manager.hh
See #571. These changes add a plugin API that passes the file name of the message to the `do_process` method of the plugin and expects a GMimeStream back -- this allows for arbitrary preprocessing of the message, including headers.
Example use case: add plain text part to HTML-only messages so that they can be quoted better when replying.
> More flexible plugin API that allows to process entire message

- src/chunk.cc
- src/chunk.hh
- src/compose_message.cc
- src/compose_message.hh
- src/message_thread.cc
- src/message_thread.hh
- src/modes/edit_message.cc
- src/modes/forward_message.cc
- src/modes/raw_message.cc
- src/modes/reply_message.cc
- src/modes/thread_view/page_client.cc
- src/modes/thread_view/thread_view.cc
- tests/test_bad_content_id.cc
- tests/test_composed_message.cc
- tests/test_convert_error.cc
- tests/test_crypto.cc
- tests/test_markdown.cc
- tests/test_mime_message.cc
- tests/test_no_newline_msg.cc
- tests/test_non_existant_file.cc
Following classes updated to use mem:
* EditMessage
* RawMessage
* Message
test in test_composed_message
> cm: use GMimeStreamMem to avoid writing tmp file

- src/compose_message.hh
- src/modes/edit_message.cc
- src/modes/edit_message.hh
use unique_ptr and close after emitting signals
#591
> cm, em: clean up references

- src/db.cc
- src/modes/edit_message.cc
- src/modes/edit_message.hh
- src/modes/mode.cc
- src/modes/thread_index/thread_index.cc
- src/modes/thread_view/thread_view.cc
- src/plugin/manager.cc
- src/plugin/manager.hh
The destructor for the thread view object didn't release all references, which lead to webkit render processes not being cleaned up after closing the thread view.
> Cleanup webkit references

- src/config.cc
By default, notmuch uses the $NOTMUCH_CONFIG environment variable in
order to find its config file. This commit makes astroid's default
config generator use this variable in order to populate the
astroid.notmuch_config setting.
> config.cc: Default astroid.notmuch_config to $NOTMUCH_CONFIG

- src/command_bar.cc
When set_text is called, an completion in an inconsistent state is triggered.
For example when the CommandBar was used for filtering (ctrl+f) and is then
used for searching (for example "O"), entry_changed will try to cast
current_completion to TagCompletion. This happens because "mode" already
contains the new mode and "current_completion" contains the old value. Thus
the cast results in an nullptr, which in turn causes an segfault.
> Prevent segfault by reordering set_text and completion setup

- src/modes/edit_message.cc
#380 #267
Not sure if this is the simplest way of doing this. I modified the logic from the place where it adds the quotes to reply messages.
> Made it not check quoted text for attachment words

- CMakeLists.txt
- Vagrantfile
- src/astroid.cc
- src/compose_message.cc
- src/config.cc
- src/message_thread.cc
- src/message_thread.hh
- src/modes/edit_message.cc
- src/modes/forward_message.cc
- src/modes/reply_message.cc
- src/utils/cmd.cc
- src/utils/cmd.hh
- tests/CMakeLists.txt
- tests/test_quote_html.cc
Update `mail.reply.quote_processor` to whatever you want to process HTML parts into text when quoting.
#319 and others.
> Quote html parts

- src/compose_message.cc
* fix incomplete markdown rendering (#585)
* for other changes see commit messages
* compiles using `CMAKE_BUILD_TYPE`s `Debug` and `Release`
* changed code compiles without warnings with `-Wall` and `-O0 -ggdb` or `-O3`
* not tested with gmime-2
> fix incomplete markdown rendering and warnings, clean compose_message.cc a bit

- src/astroid.cc
- src/plugin/astroid_activatable.c
- src/plugin/astroid_activatable.h
- src/plugin/manager.cc
- src/plugin/manager.hh
This patch adds a way to programmatically generate queries on startup.
This is done by adding a new method named "get_queries" to the
astroid_activatable interface.
Closes https://github.com/astroidmail/astroid/issues/614.
Since I still don't know how to write C++<->python interop code, I took what I feel is a particularly hackish approach. Indeed, I made the python plugin return a `[name, query, name, query…]` list instead of a list of tuples or even a map because I couldn't figure out how to have the C++ side deal with objects or lists of lists. Any help improving this part of the code is more than welcome.
> Add get_queries() extension method

- ui/part.scss
`part.scss` sets the background colour of email bodies to be white, but didn't specify a foreground colour, causing emails to be unreadable when using a dark GTK theme. Fixes #662.
> Set black text colour in email body

- src/command_bar.cc
Following on #667, I suggest removing this minimum width setting completely as Astroid already has a default size defined here:
https://github.com/astroidmail/astroid/blob/35660d486bed3c856603dcff8e8b52153e8e8da9/src/main_window.cc#L105
As a reference I found this: https://valadoc.org/gtk+-3.0/Gtk.Widget.set_size_request.html
> In most cases, set_default_size is a better choice for toplevel windows than this function; setting the default size will still allow users to shrink the window.
Thank you!
> remove minimum width for command bar

- src/modes/thread_index/thread_index_list_cell_renderer.cc
- src/modes/thread_index/thread_index_list_cell_renderer.hh
This applies the correct default font color for selected items (white on blue instead of black on blue) which make them more readable.
Maybe the subject colors could be also handled this way (didn't touch them since they are configurable).
> Use colors with the correct gtk state flag

- .github/workflows/ci-debian-build-test.yml
I'd like to think #676 could have been caught sooner, if there was continuous integration testing. And presumably other changes that have caused build failures in master could have been caught sooner.
Here's a [GitHub Actions](https://help.github.com/en/actions) config to run builds on a range of Debian and Ubuntu releases. You could easily add other distributions using the same approach.
This will need some maintenance over time:
1. Updating the list of releases to test on. Ubuntu devel points to the current development release, but the other supported LTSs are named.
1. Updating build dependencies. This might require hacks like the `apt-get ... || apt-get ...` I used here. In the future `apt-get satisfy` will be a nice solution for that kind of thing, but it's only available from apt …
> GitHub action to build on Debian & Ubuntu

- tests/test_composed_message.cc
Test regressed under gmime 3.2.3, because of the change in jstedfast/gmime@2dd1be81555d787ff1ff03b11e5cb4b9e81630d6
A trailing newline was added to the text/plain message body in the test, causing the round-trip comparison to fail.
Fixes: #676
> End test email message bodies with a trailing newline

- shell.nix
This might be a bit of a controversal PR here, but anyways:
I'd like you to include this `shell.nix` file for firing up a quick development environment by executing `nix-shell` in the project root.
The `configure`, `build`, `run` and `debug` commands can then be used to ... well... configure, build, run and/or start astroid in gdb.
> Add shell.nix for development environment

- src/modes/thread_index/query_loader.cc
The function notmuch_query_search_threads() only [sets the pointer on success](https://github.com/notmuch/notmuch/blob/2b62ca2e3b786beca8d89fa737bda0b49faa638d/lib/query.cc#L532-L533).  Not initializing the pointer could result in an abort or segfault in notmuch_threads_destroy() due to it pointing to whatever was previously on the stack.
> ql: Default initialize threads to NULL.

- src/config.cc
- src/main_window.cc
- src/modes/keybindings.cc
- src/modes/thread_index/thread_index_list_view.cc
before this was silently relying on boost placeholders, but those
default off now.
> use std::placeholders everywhere

- src/modes/edit_message.cc
In adwaita-icon-theme 42, the non-symbolic versions were removed from
the standard distribution. Therefore, switch to the symbolic versions.
I don't know where gtk-apply comes from, so I didn't change that.
> Use symbolic icons (fixes #715)

- src/utils/address.cc
In the console, I am frequently seeing the following assertions being triggered.
```
(astroid:1774218): gmime-CRITICAL **: 18:25:20.896: internet_address_list_length: assertion 'IS_INTERNET_ADDRESS_LIST (list)' failed
(astroid:1774218): gmime-CRITICAL **: 18:25:20.896: internet_address_list_length: assertion 'IS_INTERNET_ADDRESS_LIST (list)' failed
[18:25:20] [0x00007fffc2d6c6c0] [M] [error] address: no address in string.
```
Silence this by checking `IS_INTERNET_ADDRESS_LIST` before calling `internet_address_list_length`.
> Fix gmime assertions being triggered by invalid addresses

- src/compose_message.cc
Attaching a file caused segfaults with some versions of glib. It turns out that when attaching a file, it is loaded as a byte array in `compose_message.cc`.  For this a Gio smart pointer is obtained by wrapping the GFile pointer. The wrapping has to copy, i.e. `wrap(,,, true)`, because the pointer will smartly cleanup when going out  of scope, and then also the GFile pointer when getting unreferenced. This is my explanation for this pull request.
> compose_message: to load as byte array, 'file' must be wrapped with copy

- src/config.cc
- src/modes/thread_index/thread_index_list_cell_renderer.cc
- src/modes/thread_index/thread_index_list_cell_renderer.hh
Currently, there is no option to disable the left icons (e.g., attachment, urgent). However, they take up valuable screen real-estate on mobile devices. Others may simply find them less useful and want to hide the extra visual clutter.
For these reasons, this adds a config option and associated rendering logic to hide these icons upon request.
> Add option to disable left icons

- src/db.cc
- src/modes/thread_index/thread_index_list_view.cc
- src/modes/thread_index/thread_index_list_view.hh
- src/modes/thread_view/thread_view.cc
Currently, Astroid has no support for deleting messages. Without deleting messages, a mail server with limited storage will eventually become full and incapable of receiving any more mail. Message deletion functionality in clients is an important mechanism for preventing this.
This adds a mechanism to mark messages as 'trash' in Astroid, which servers like gmail are configured to interpret as a deletion request.
> Add a '#' key to send a message to the trash.

- src/main_window.cc
Currently, this opens an empty sidebar on the left part of the window and displays a cut-off help message in a ribbon at the bottom of the window. The sidebar does not go away until exiting and re-opening the app. This change removes this behavior to improve usability while keeping the original intent in the code to track the feature for future contributors see the contribution opportunity.
I would also be open to deleting these lines.
> Fix help message breaking screen layout

- src/modes/edit_message.cc
they are the same, but is_regular_file is standard so boost removed is_regular
> em: is_regular -> is_regular_file

- src/modes/thread_view/page_client.cc
- src/modes/thread_view/page_client.hh
- src/modes/thread_view/thread_view.cc
- src/modes/thread_view/webextension/tvextension.cc
- src/modes/thread_view/webextension/tvextension.hh
- ui/thread-view.html
- ui/thread-view.scss
- fixes #720, fixes #736
- closes #732, closes #740, closes #743
This does not allow the document (message content) to execute javascript, as can be verified with the following email, which displays "no scripts" by default, but "scripts active" when js is active.
```
Date: Tue, 1 January 1970 00:00:00 +0000
From:
Subject:
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="=-TUjG03Ah9OcLtWE56Ucm"
--=-TUjG03Ah9OcLtWE56Ucm
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
<div id=3D"jscontent">
no scripts
</div>
<script>
d =3D document.getElementById('jscontent');
d.innerHTML =3D "scripts active";
</script>
--=-TUjG03Ah9OcLtWE56Ucm
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable
<!DOCTYPE html>
<html …
```
> set iframe height in javascript

- src/main_window.hh
GtkHBox has been deprecated since GTK 3.2.  No further changes are needed, since the default value of the GtkOrientable:orientation property is GTK_ORIENTATION_HORIZONTAL.
(See: https://docs.gtk.org/gtk3/class.HBox.html)
> Stop using deprecated Gtk::HBox

- src/astroid.hh
- src/db.cc
Under certain circumstances - both deterministic and non-deterministic - astroid can segfault on exit.
For example, when there's another window already running:
```
$ astroid & bg
[2024-06-05 16:18:20.526090] [0x0000706fccadcec0] [info]    welcome to astroid! - v0.16-20-g41808e88
...
[16:18:20] [0x0000706fccadcec0] [M] [debug] log: stdout: yes
$ astroid 
[2024-06-05 16:20:26.487138] [0x00007f11b1bbaec0] [info]    welcome to astroid! - v0.16-20-g41808e88
Segmentation fault (core dumped)
```
In all cases the cause is at least one of these pointers pointing at garbage due to being uninitialised.
> Default initialize all pointers in Astroid class to avoid segfault in dtor

- src/main_window.cc
1. Sets equal margins on both top and bottom, which (to me) has a better aesthetic look to it.
2. I noticed that there was a typo in the code which meant the bulk update ("multi") revealer never got a margin set.
---
Before this PR:
---
After this PR:
---
> Set margin_top on the revealer bars in addition to margin_bottom

- src/modes/paned_mode.cc
Otherwise the second child gets no width, and appears to be hidden when a thread is opened in pane view.
The number `300` is pretty arbitrary, it's taken as 1/4 of the default window width ([set here](https://github.com/astroidmail/astroid/blob/c1e5cdbd662e2bcfef2fe5dc72dbc444a692a0e8/src/main_window.cc#L105)).
Fixes #547
> Call set_size_request on pane children

- src/main_window.cc
This reverts commit 8f2a8aeefd634c3f861ba51f7ca5fe256c7350b1.
There is no other place in the code that calls `rev_multi->set_reveal_child(true)`, so the consequence of this change was that the `;` key no longer shows the revealer bar.
Before this PR:
After this PR:
> Fix help message for actions on multi-message-selection
